### ISSUE TITLE
word-length metric balls computation fails?

### ISSUE THREAD

**Issue by piotrmizerka** [kalmarek/Groups.jl#28]
Hey, I noticed that the Groups v0.7.6 computes balls wrongly: the issue occurs in the function "group_ring" from this file https://github.com/piotrmizerka/LowCohomologySOS/blob/2207.02783/src/group_rings.jl

When running tests on branch 2207.02783 of LowCohomologySOS (Julia version 1.8.3), the test 

`Test "@test Set(collect(b)) == Set([[a]; [a^i for i in 2:n]])`

fails (this test is a part of @testset "group_ring"  from "group_ring_tests.jl" from LowCohomologySOS.

**Comment by kalmarek** [comment]
can you condense the failing example to code which only uses Groups.jl?

**Comment by piotrmizerka** [comment]
```
using Groups

function cyclic_group(n::Integer)
    A = Alphabet([:a, :A], [2, 1])
    F = FreeGroup(A)
    a, = Groups.gens(F)
    e = one(F)
    Cₙ = FPGroup(F, [a^n => e])

    return Cₙ
end

const N = 15
Cₙ = cyclic_group(N)
S = gens(Cₙ)
S_inv = unique([S; inv.(S)])
ball, _ = Groups.wlmetric_ball(S_inv, one(Cₙ), radius = N)

@assert length(ball) == N
```
